### ISSUE TITLE
Does the reference encoder support 1/2/3 channels, or uncorrelated X+Y?

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#19]
This is touted in all of the talks and discussions about ATSC, but it doesn't help if the encoders don't generate the data.   Does the encoder support these modes?  I can sometimes get 3 channels from the encoder, but most often it defaults to 4 channels.   The encoders I've found all use 3 or 4 channels, but isn't the compression considerable with 1 or 2 if you have a 1 or 2 channel texture?  I'm looking for the equivalent of BC4 and BC5, which ATSC was supposed to encompass.

**Comment by solidpixel** [comment]
The reference encoder does support this. 

For compressing two channel normal maps remember to specify the `-normal_psnr` command line option.

Also note that unlike most compression formats, ASTC doesn't have a fixed encoding format for the entire texture, the only thing which is fixed is the block size. The encoder is free to choose on a block-by-block basis what encoding mode to use, so it can be a little variable depending how the error metrics play out based on the local color patterns in the block being compressed. 

If you can share the image you want to compress and the command line you are trying, I can take a look at it.

Cheers, 
SP

**Comment by alecazam** [comment]
I'm still not sure how a shader is supposed to respond to X+Y mode if it's stored as RGBA=XXXY unless all blocks are stored that way.  A shader would need to know to reconstruct z with a swizzle for those blocks - nmap.ag swizzle in this case.  They certainly can't query the format, since all ASTC textures report the exact same format.

EAC_RG11/BC5 all return XY in RG, so I'm not sure why ASTC decided to use the BC3nm-style swizzle.  Am I confusing an LA mode with X+Y mode which is special?

I just haven't dug into the CEM blocks enough to see if the encoders are really using the single channel and dual channel modes (X+Y).  If you can verify that, then I'd like to know it's more than astcenc shuffling the data to XXXY and then using the regular RGBA (single correlated gradient).  There's a big difference between storing an normal map in BC5 vs. BC1.  The gradient count on BC5 is 2, and on BC1 it's only 1.  My concern is that the encoders all just use a single gradient regardless of the channels.

**Comment by alecazam** [comment]
I guess when I did run tests with astcenc, I never saw it report 2 channels.  It said there were three or 4.  Even on single channel textures, it would report 3 or 4.  Inferring that ASTC_RGBA is a normal map from an assumption that it took X+Y mode in the encoder isn't probably good long term for this format.  This was also an issue for BC3nm, but BC5 fixed that.

**Comment by alecazam** [comment]
Also why is astcenc exporting single astc files?  No one supports this format for viewing or import.  etcpack supports mips and ktx exports.  Can these two command line tools offer at least these similar options.  I can use PVRTexToolCLI to then build the KTX files, but it has serious bugs of it's own, so it would be nice to go direct to astcenc and get a mip or array or cubemap ktx file out.

**Comment by solidpixel** [comment]
> I'm still not sure how a shader is supposed to respond to X+Y mode if it's stored as RGBA=XXXY unless all blocks are stored that way. 

As you hint as, all blocks must be stored that way or it couldn't work. See the documentation for the `-normal_pnsr` flag in the encoder - green channel is moved to the alpha channel index before encoding. 

> A shader would need to know to reconstruct z with a swizzle for those blocks - nmap.ra swizzle in this case. 

Yes. As per the above, given the data is known to be in a `.ra` swizzle you can deterministically decode it.

> Inferring that ASTC_RGBA is a normal map from an assumption that it took X+Y mode in the encoder isn't probably good long term for this format. 

The encoder doesn't really "know" - one of the relatively unique things about ASTC is that the color format, color end points, and plane selections are all mutable on a block by block basis. The only thing which makes a normal map "special" is the fact that you switch the encoder across to an angular error metric for measuring encoding quality.

> I also didn't see use of the X+Y CEM in the reference encoder. Can you point me to where that might be done. 

The CEM just describes the plane layouts and decode type. From a CEM point of view "X+Y" is simply two independent LDR channels, so it will use LDR Luminance + Alpha, which is really the same thing.

> The gradient count on BC5 is 2, and on BC1 it's only 1. My concern is that the encoders all just use a single gradient regardless of the channels.

ASTC can use either one or two planes, chosen on a block-by-block basis. As per my first comment, don't get hung up on the block format in use - using two planes when it isn't needed decreases image quality because you waste bits encoding the second set of plane data. If you want to compare formats in any meaningful way you need to use some form of image PSNR error metrics.

> EAC_RG11/BC5 all return XY in RG, so I'm not sure why ASTC decided to use the BC3nm-style swizzle. 

If you want to use a separate non-correlated plane in ASTC it has to be in the alpha channel location in the encoded data. Supporting R+G as well as R+A would add another CEM index which would require more encoding bits and therefore would reduce compression rate which is something we wanted to avoid when designing the format for obvious reasons.

If you want to maintain the `.rg` channel ordering to be consistent with the other formats from a shader point of view, then it is trivial to do so by setting up a sampler swizzle in the rendering API for your ASTC textures (i.e. set `GL_TEXTURE_SWIZZLE_G` to `GL_ALPHA`) .

HTH, 
Pete

**Comment by alecazam** [comment]
The inference isn't to the encoder, but I'll get to that issue after this.

The reference decoder default requires a .ga swizzle (or .ra - but it's rrrg). The reason I recommend that over .rg is for BC3nm, where g has 6 bits, and ba may not be grayscale data.
   -normal_psnr -> "-rn -esw rrrg -dsw raz1 -ch 1 0 0 1 -oplimit 1000 -mincorrel 0.99" .

So the encoder should also use X+Y if I specify the following.  This would be a .ag swizzle.
   -esw gggr 

So now there are two ways to encode the X+Y, and here's where the inference comes in.  It's the inference to shader that is the big issue.   You can setup a swizzle, but the app needs to know from the texture what path to take and tell the shader whether to use .rg, .ga, .ag swizzle (or use the sampler swizzle).  WebGL, for example, decided not to expose swizzles so this requires shader modification or splicing or assumptions about the incoming format is all the same encoding.

KTX could store the data if it specified GL_LUMINANCE_ALPHA instead of GL_RGBA in the file.  At least then the full encoding would be captured in the file itself.

Thanks so much for the discussion on this.  You comments have been very helpful.  I'm surprised at some of the choices that were made in the format and reference encoder.

So now, I have a bunch of compressed normal map png textures out there in the world.  There are no guidelines on how to pre-swizzle the data, but I think these are the rules.    The pre-swizzle is what you must use in content tools to get ASTC to take the more optimal path of encoding L or L+A.  The post-swizzle is what the sampler or shader must execute.

Channels.   Formats                                                             Pre-Swizzle.              Post-swizzle       
1.                 BC4,EAC_R11,     ASTC(L)                                 rrr1                             .r or.g or .b
2.                BC5,EAC_RG11/ASTC(L+A),BC3nm(G+A)       rg01/(rrrg or gggr).   .rg/(.ga or .ag)

If you don't follow these rules exactly with ASTC, then you don't get the optimal path.  For example:

a.  I use r001 for single channel textures, but then ASTC doesn't realize that's encodable to L (Lum). (use .r, but don't get single channel or multiple partitions?)
b.  I use rg01 for my normal maps, but then it's encoded as 3 channel rgb and not L+A (use .rg)
c.  I use rgb1 for my normal maps, but then it's encode as 3 channel rgb (use .rg)

There are a lot of ASTC normal map textures created with c (or less likely b).  I don't even see an option in PVRTexToolCLI to set the -normal_psnr mode.

Your ASTC encoder is storing data in the opposite order from BC3nm and BC5_LATC modes. Note that no encoding tools I've seen expose LATC, they just expose BC5_RGTC,
 
https://github.com/castano/nvidia-texture-tools/wiki/NormalMapCompression
BC3nm (DXT5nm) - " It uses a DXT5 block to represent normals, storing the X component in the Alpha and the Y component in the Green channel."

So .ag (not .ga) is the standard swizzle for BC3nm, and BC5_LATC, but your reference encoder does the opposite.  So now we have normal maps with inconsistent reconstruction methods.

    -esw rrrg -dsw raz1.  <- this uses .ga

**Comment by solidpixel** [comment]
I'd never realized WebGL decided not to expose API-side swizzles; that does indeed make hiding format differences a bit of a pain.

Your current table looks OK, except for the fact that the current settings for `-normal_psnr` set the error weighting factors for the `g` and `b` components pre-encoding to zero, as it assumes they are not going to be read, so the current reference encode could write complete garbage into those two channels (it's not guaranteed to pick a Luminance + Alpha block), because they don't factor into the PSNR calculations.


The pre-swizzle of `-esw gggr` looks fine to do the reversal of X and Y, but I'd be very wary of a post-swizzle of `.ag` because I'm not sure you get any strong guarantee about what `g` contains.

**Comment by alecazam** [comment]
I was able to crack apart the blocks and validate that rg01 results in RGB single-plane encoding and rrrg (or gggr) results in LA dual-plane encoding.  An important detail to convey to content creators and the shaders that support the format.

Keep in mind that ga/ag formats like BC3nm and ASTCnm make it very challenging to view the resulting texture compared to RG, since the second component is in the alpha channel.  You need specialized texture viewers that know it's an ASTCnm and not an ASTCrg file.  L and LA support was also removed from ES3 in favor of swizzles on R/RG, but then APIs like WebGL2 left out swizzle support.

**Comment by alecazam** [comment]
There are issues with requiring L+A (GGGR or RRRG) to get dual-plane vs. RG01 (single-plane).  
    1. L+A is processed differently than RG01 when the SRGB flag is set.  A is unaffected.
    2. There are unused bits reserved for unused HDR modes in the LDR format.    
    3. Specialized texture viewers are needed when data is stuffed into alpha (f.e. DXT3nm and ASTCnm).  Most viewer pre-multiply alpha.
    4. L+A was left out of HDR mode, but with PBR you have a lot of single and double channel textures.
    5. No way to do Gray Gamma 2.2 dual-plane using 2 channel SRGB modes (because of L+A).
   
In addition, 3D ASTC (4x4x4) is inconsistently supported now.
    1. BC and ETC and PVRTC don't offer this mode making encoders more complicated.
    2. Many KTX importers expect volume textures with the ASTC 2D formats, not the 3D formats.

There's still more issues on the encode side.
    1. astcenc can take 20s or more per texture, which doesn't scale well to dynamically generated content.
    2. no GPU-based encoders like for BC.
    3. astcenc can't spit out KTX files, but you can so so indirectly via PVRTexTool
    4. PVRTexTool can't generate 3D textures, and has an sRGB conversion bug

**Comment by LuckyStarProg** [comment]
@alecazam @solidpixel   Seems that I have similar issue?
I am trying to compress my normal maps for my iOS game, but by default I receive some noise even in 4x4 block sizes. After further research I have found  -normal_psnr, but it makes texture in green Chanel (image attached).
I am using  Mali texture Compression Tool.
What I am doing wrong ?
Sorry for this question, I am pretty new in he field
![tex_photo_frame_01_woodoak_smooth_default_n](https://user-images.githubusercontent.com/19596973/44177747-e8eccf00-a0f7-11e8-9b02-ecee2ad38427.png)
<img width="415" alt="2018-08-16 01 59 46" src="https://user-images.githubusercontent.com/19596973/44177808-31a48800-a0f8-11e8-8e93-1c1d823bcfd2.png">
<img width="600" alt="2018-08-16 02 00 19" src="https://user-images.githubusercontent.com/19596973/44177812-349f7880-a0f8-11e8-9756-b1e22258bfa5.png">
<img width="534" alt="2018-08-16 02 00 08" src="https://user-images.githubusercontent.com/19596973/44177816-3701d280-a0f8-11e8-8e5d-f521aa106a8d.png">

**Comment by prideout** [comment]
Hey @alecazam, when you said "So there are many ASTC encoders out now.", did you mean "So there are **not** many ASTC encoders out now."?

**Comment by solidpixel** [comment]
Closing - original question was answered.

**Comment by alecazam** [comment]
Despite the suggestion above, it appears that the Mali tool still dumps out .astc files for each mip, and the ktx option is only provided for ETC1/2 output.

**Comment by solidpixel** [comment]
The Mali Texture Compression tool is not under active development, and doesn't have any future releases planned at the moment, so I wouldn't expect to see any significant changes there. 

Getting astcenc to spit out a full mipchain in KTX format is something which is worth looking at - I'll raise a separate issue for that one.

**Comment by alecazam** [comment]
There was as thread on Twitter, but it sounds like ASTC supports a BC5/EAC_RG11 type dual plane mode for RG01.  This stores RGB endpoints, but sets dual-plane bits.  One plane for RB = R0, and another for G.  That burns 4 x 8-bits storing a blue channel that is all 0, but avoids the LLLA swizzle in the shaders.  Not sure it's worth burning up 1/4 of the bits of each block though, since LA only stores 2 channel endpoints.

**Comment by solidpixel** [comment]
Any single channel can be the "dual plane" - it doesn't need to be alpha. 

The number of bits used to store the blue channel depends on the endpoint quantization level and the number of planes. Worst case you're storing 8 values (4 planes, two endpoints per plan), but most blocks use 1 or 2 planes.

**Comment by alecazam** [comment]
I think the posts were in reference to this table in the spec.  And there is channel pairing according to this, and no guarantees that various encoders actually set these bits, so just wanted to verify.

![image](https://user-images.githubusercontent.com/3750359/91483211-2f837100-e85c-11ea-9e9d-3dc1280bdca4.png)

**Comment by solidpixel** [comment]
> These modes interpolate B/A, but if they're constant = 01 then hopefully they wouldn't be stored.

The B component will still need storing. ASTC has no endpoint which allows storing only RG. You would need to store it as a three component RGB endpoint, storing blue. The three color endpoints gives the the 1.0 alpha for free. 

> but I'd assume most ASTC data uses full 4 channels [in the texture cache] for RGBA regardless of content

Yes, the format is always 4 channels post-decompression.
